learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views


app_name = 'basic_app'


urlpatterns=[
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='user_login'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^basic_app/', include('basic_app.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^special/$', views.special, name='special'),
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=0)

    portfolio = models.URLField(blank=True)
    picture = models.ImageField(blank=True, upload_to='profile_pics')

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio', 'picture')

learning_users/basic_app/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout


def index(request):

    return render(request, 'basic_app/index.html')


@login_required
def user_logout(request):

    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponse('You are logged in , niiiice!')


def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html',
                  context={'user_form':user_form,
                           'profile_form': profile_form,
                           'registered': registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")
        else:
            print('someone tried to login and failed')
            print('username: {} and password {}'.format(username,password))
            return HttpResponse('ivalid login details supplied')
    else:
        return render(request, 'basic_app/login.html', {})

learning_users/templates/basic_app/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>

     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'index' %}" class="navbar-brand">Django</a></li>
                <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin</a></li>

                <li><a href="{% url 'basic_app:register' %}" class="navbar-link">Register</a></li>

                {% if user.is_authenticated %}
                        <li><a href="{% url 'logout' %}" class="navbar-link">Logout</a></li>
                {% else %}
                        <li><a href="{% url 'basic_app:user_login' %}" class="navbar-link">Login</a></li>

                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block bodyblock %}

        {% endblock %}
    </div>
</body>
</html>

learning_users/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django Level Five</h1>

</div>

{% endblock %}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% load staticfiles %}

{% block bodyblock%}
    <div class="jumbotron">
        <h1>please login</h1>
        <form class="{% url 'basic_app:user_login' %}" method="POST">
            {% csrf_token %}
            <label for="username">Username: </label>
            <input type="text" name="username" placeholder="enter username">

            <label for="password">Password: </label>
            <input type="password" name="password">

            <input type="submit" value="Login">
        </form>
    </div>
{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load staticfiles %}

{% block bodyblock%}
    <div class="jumbotron">
        {% if registered %}
            <h1>Thank You for registering!</h1>
        {% else %}
            <h1>Register Here!</h1>
            <h3>Fill out the form:</h3>

            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}

                <input type="submit" value="Register">
            </form>
        {% endif %}

    </div>
{% endblock %}