CBVs/advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from basic_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view()),
    url(r'^basic_app/', include('basic_app.urls', namespace='basic_app')),

]

CBVs/advcbv/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'
urlpatterns = [
    url(r'^$', views.SchoolListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name='detail'),
    url(r'^create/$', views.SchoolCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name='delete'),
]

CBVs/advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class School(models.Model):
    name = models.CharField(max_length=100)
    principal = models.CharField(max_length=50)
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('basic_app:detail', kwargs={'pk': self.pk})


class Student(models.Model):
    name = models.CharField(max_length=100)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=0)

    def __str__(self):
        return self.name

CBVs/advcbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from . import models
from django.urls import reverse_lazy


class IndexView(TemplateView):
    template_name = 'index.html'


class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'


class SchoolCreateView(CreateView):
    model = models.School
    fields = ('name', 'principal', 'location')


class SchoolUpdateView(UpdateView):
    model = models.School
    fields = ('name', 'principal')


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('basic_app:list')

CBVs/advcbv/basic_app/templates/basic_app/basic_app_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class='navbar-brand' href="{% url 'basic_app:list' %}">Schools</a></li>
            <li><a class='navbar-link' href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class='navbar-link' href="#"></a></li>
        </ul>
    </nav>
    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>


</body>
</html>

CBVs/advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}

<h1>Delete {{ school.name }}? </h1>
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
</form>

{% endblock %}

CBVs/advcbv/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Welcome to the School Detail Page</h1>
        <h2>School Details</h2>
        <p>Name:      {{ school_detail.name }} </p>
        <p>Principal: {{ school_detail.principal }} </p>
        <p>Location:  {{ school_detail.location }} </p>

        <h3>Students: </h3>
        {% for student in school_detail.students.all %}
        <p> {{student.name}} who is {{student.age}} years old.</p>
        {% endfor %}
    </div>
    <div class="container">
        <p>
            <a href="{% url 'basic_app:update' pk=school_detail.pk %}" class="btn btn-warning">Update</a>
            <a href="{% url 'basic_app:delete' pk=school_detail.pk %}" class="btn btn-warning">Delete</a>

        </p>
    </div>

{% endblock %}

CBVs/advcbv/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}

<h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif %}
</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Submit">
</form>

{% endblock %}

CBVs/advcbv/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}

<h1>Welcome to a list of all the schools.</h1>
<ol>
    {% for school in schools %}
        <h2><li><a href="{{ school.id }}"> {{ school.name }}</a></li></h2>
    {% endfor %}
</ol>
{% endblock %}

CBVs/advcbv/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class='navbar-brand' href="{% url 'basic_app:list' %}">Schools</a></li>
            <li><a class='navbar-link' href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class='navbar-link' href="#"></a></li>
        </ul>
    </nav>
    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>


</body>
</html>

CBVs/advcbv/templates/index.html
{% extends 'base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>Home Page</h1>
</div>
{% endblock %}